### ISSUE TITLE
index page updates to promote specific Authors and posts by Tag

### ISSUE THREAD

**Issue by smcnally** [smcnally/extro-hueman-pro-child#1]
The first available slot in the grid on **index** and **archive** pages for 
the latest from particular 

1) author id(s) or 2) item source(s) (`tag=sourceName` or `meta_key='wprss_item_permalink'`) 
by a) category or b) tag 

First available slot atm is sometimes a Sticky, but is usually the first slot in the grid.
LIFO / reverse chron so most-recently updated

### index / archive pages

![image](https://user-images.githubusercontent.com/850878/35478095-3330e70c-03a2-11e8-9f6a-0925ec9dea62.png)

https://extroverting.com/tag/northeast/

### Authors and item sources
e.g. 

Brad's (`author=9`) latest by tag and category should go to the first available slot 

His **[_Canadian Cannabis Companies Search for Workers Ahead of Legalization_](https://extroverting.com/2018/01/20/canadian-cannabis-companies-search-for-workers-ahead-of-legalization/)** post would go to the first available slot on the posts' cats & tags index pages including [**Canada**](https://extroverting.com/category/canada/), [**Cannabis Abroad**](https://extroverting.com/category/cannabis-abroad/), and [**Cannabiz**](https://extroverting.com/category/cannabiz/)

### Sources

Some sources are better than others and we want to highlight and promote those.

We'll id these sources by tag for now, e.g.

https://extroverting.com/tag/the-union/

(there are updates we want to make per post page for these good sources, too. another ticket.

**Comment by smcnally** [comment]
This Issue and https://github.com/smcnally/extro-hueman-pro-child/issues/2 involve the same files. Let's consider them together even if we plan to work on them separately.

**Comment by smcnally** [comment]
FAR is added as contributor to this repo. Please create your own branch. 

An Extroverting db backup from today is here:

https://extroverting.com/tag/shepherd/2018-02-14-15-16.gz

The hueman (**parent**) theme is here:

https://wordpress.org/themes/hueman/

And the **child** theme -- where all work should be done -- is this repo:

https://github.com/smcnally/extro-hueman-pro-child

which goes in 

`wp-content/themes/extro-hueman-pro-child`

just like hueman does

`wp-content/themes/hueman`

**Comment by FARCreative** [comment]
Where and in which way should we set prioritized authors or tags in the admin area?

**Comment by smcnally** [comment]
Let's please work on https://github.com/smcnally/extro-hueman-pro-child/issues/2 first. 

For this ticket https://github.com/smcnally/extro-hueman-pro-child/issues/1

> Where and in which way should we set prioritized authors

For now, prioritized authors are **user_id 9** and **user_id 15**

> prioritized tags

All posts posts by **[user_id 9](https://extroverting.com/author/brad/)** and **[user_id 15](https://extroverting.com/author/emmettnelson/)** get priority for all tags and categories used on their posts. 

Brad (**[user_id 9]**) uses the **Investing** tag on his latest post. 

https://extroverting.com/2018/02/16/the-one-number-that-matters-for-the-hottest-marijuana-stocks/

That post should remain first on the investing tag page here
https://extroverting.com/tag/investing/

Until (**[user_id 9]**) has a newer post using the **Investing** tag

This same post also includes Canada and Cannabiz categories. 
So this same post should remain the first item on page 1 of the **[Canada](https://extroverting.com/category/canada/)** and **[Cannabiz](https://extroverting.com/category/cannabiz/)** category index pages. 

https://extroverting.com/category/canada/
https://extroverting.com/category/cannabiz/

Let's please work on https://github.com/smcnally/extro-hueman-pro-child/issues/2 first. 
We'll come back to this.

**Comment by FARCreative** [comment]
I have updated categories and tags posts listing to display specific authors latest posts at the top of the list. Also these posts are highlighted with light green background (Did I undersood your mockup correctly?). Specific authors (ids 9 and 15) are hardcoded  in the function.php file at the moment.

**Comment by smcnally** [comment]
I will create a new ticket to supersede this one. The new ticket will simplify my ask re promoting specific authors & sources. Will leave https://github.com/smcnally/extro-hueman-pro-child/issues/1 open for now. You're on the right track already, but there are issues:

updated your latest `farcreative` branch. With that branch active in [Prod](https://extroverting.com), only one story item is rendered to the page, and that item is not visible. I've moved back to `master`.  

Here's a screenshot and page source from [Investing](https://extroverting.com/tag/investing/) when `farcreative` was active. 

![image](https://user-images.githubusercontent.com/850878/36673366-90d20d38-1ad0-11e8-82db-44225b0463dd.png)

[180226-Extro_tag_Investing-Page_Source.txt](https://github.com/smcnally/extro-hueman-pro-child/files/1758793/180226-Extro_tag_Investing-Page_Source.txt)

**Comment by smcnally** [comment]
Handled (better) in #4
