### ISSUE TITLE
Giving top news sources logos with links back to their site on archive pages

### ISSUE THREAD

**Issue by smcnally** [smcnally/extro-hueman-pro-child#2]
On **archive** pages, I want to add logos for our top news sources. e.g. **archive** pages for 3 top sources are these:

https://extroverting.com/tag/cannabist-co/ 
https://extroverting.com/tag/washington-post/ 
https://extroverting.com/tag/boston-herald/ 
	
archive pages include all /**tag**/ and /**category**/ pages. We won't create special pages for top sources; we'll **_add rules to all archive pages to include logos and links if we have them_** and show nothing extra if we don't.

Presume the logo image file will always be in the same location, e.g. 	
	`wp-content/uploads/sites/3/{tag-name}-logo.png`
Presume the logos are the same height and width
if there isn't a logo for a given archive page, it should fail gracefully / no broken image icon. 

https://extroverting.com/tag/boston-herald/ would look like ~this:

![image](https://user-images.githubusercontent.com/850878/36181735-25bf9f28-10f4-11e8-88fa-289fe9a25a9a.png)

The Boston Herald logo links to http://www.bostonherald.com/

The theme code involved is available here: https://github.com/smcnally/extro-hueman-pro-child

Requests for https://extroverting.com/tag/boston-herald/ (and all archive pages) calls these files (if you need others, we'll copy them from the parent to the child theme):

[/extro-hueman-pro-child/archive.php](https://github.com/smcnally/extro-hueman-pro-child/blob/master/archive.php)
which calls
	[/extro-hueman-pro-child/tmpl/archive-tmpl](https://github.com/smcnally/extro-hueman-pro-child/blob/master/tmpl/archive-tmpl.php)
which calls
		[/extro-hueman-pro-child/parts/post-list-articles.php](https://github.com/smcnally/extro-hueman-pro-child/blob/master/parts/post-list-articles.php)

Let me know in the comments if this is enough to start, if I can provide more information, and your estimates for start and completion time.

**Comment by smcnally** [comment]
This Issue and https://github.com/smcnally/extro-hueman-pro-child/issues/1 involve the same theme files. Let's consider them together even if we plan to work on them separately.

**Comment by smcnally** [comment]
FAR is added as contributor to this repo. Please create your own branch. 

An Extroverting db backup from today is here:

https://extroverting.com/tag/shepherd/2018-02-14-15-16.gz

The hueman (**parent**) theme is here:

https://wordpress.org/themes/hueman/

And the **child** theme -- where all work should be done -- is this repo:

https://github.com/smcnally/extro-hueman-pro-child

which goes in 

`wp-content/themes/extro-hueman-pro-child`

just like hueman does

`wp-content/themes/hueman`

**Comment by smcnally** [comment]
> We can store logo images in hardcoded folder wp-content/uploads/sites/3/ 

Great

> and upload files using FTP or something else

Presume we'll put the logo files up in `wp-content/uploads/sites/3/` 

> but how should we store the logos links?

I've created a new user type called `News Source`. 

**Boston Herald** is `user_id=17`

Please get the logo link from the `url` value of the profile.

We'll start first with **Boston Herald**. Your code will let us note the `user_id` and **logo file name**

Once you have that completed, let's review.

**Comment by FARCreative** [comment]
I have created a new branch 'farcreative' and upload our code there.
As I understand, you will create special new users with nicename similar to the source tag or category name (e.g. nicename of Boston Herald should be boston-herald).
Our code search this user by his slug using current tag or category name. If user exists and has website url, this link will be added to the logo, otherwise we will display just image.

**Comment by smcnally** [comment]
Thanks, Evgeny. 

> you will create special new users with nicename similar to the source tag or category name (e.g. nicename of Boston Herald should be boston-herald).

Making the nickname similar to the source **tag** or **category** name is a good idea. 

I've made the nickname for [bostonherald](https://extroverting.com/wp-admin/user-edit.php?user_id=17) boston-herald

Presume we will do the same for the others. 

> Our code search this user by his slug using current tag or category name. If user exists and has website url, this link will be added to the logo, otherwise we will display just image.

Excellent

**Comment by smcnally** [comment]
You can create the "**News Source**" role on your local environment by adding this to [functions.php](https://github.com/smcnally/extro-hueman-pro-child/blob/master/functions.php) in this child theme:

We'll create all these "users" with the "News Source" role
cannabist-co, washington-post, boston-herald, etc.


```
<?php
add_role('news_source', __(
    'News Source'),
    array(
        'read'              => true, // Allows a user to read
        'create_posts'      => true, // Allows user to create new posts
        'edit_posts'        => true, // Allows user to edit their own posts
        'edit_others_posts' => false, // Allows user to edit others posts too
        'publish_posts'     => true, // Allows the user to publish posts
        'manage_categories' => true, // Allows user to manage post categories
        )
);
?>
```

**Comment by smcnally** [comment]
Logos for **boston-herald**, **washington-post**, and **nj-com** have been added to these users' profiles as `user-profile-picture`

`nickname`s are as above to match their tags. 
Site address is `url` attribute of the user profile.  

https://extroverting.com/tag/boston-herald/
https://extroverting.com/tag/washington-post/
https://extroverting.com/tag/nj-com/

Please use user profile attributes for logos / avatars vs storing logo files in /`uploads`. 
That work for you, @FARCreative ?

**Comment by FARCreative** [comment]
Yes, we can use user's avatar for logo. I have pushed updates to 'farcreative' branch.
Now I use wp function get_user_meta($user_ID, 'wp_user_avatar') to get avatar. It searches custom avatars uploaded for users. 
If it doesn't work for you, please describe which plugins or which code updates you are using to add custom avatars to users.

**Comment by smcnally** [comment]
Thank you. We'll test theme changes in the **farcreative** branch and respond here. 

We're currently using default WP functions for user avatars through **Gravatar**. 
`get_user_meta($user_ID, 'wp_user_avatar')` should work well & we'll confirm.

boston-herald:
https://en.gravatar.com/userimage/9107/098a0692e29330f2ad1d0a32e56c82c6.jpg

nj-com:
https://en.gravatar.com/userimage/9107/10bd8b4517436fabf3afb7ca8742eb6c.jpg

washington-post:
https://en.gravatar.com/userimage/9107/2fe9280950639cf7593399326da98317.jpg

Will provide details of testing.

**Comment by smcnally** [comment]
Production is on **farcreative** branch.
I'm not seeing changes on any of these:

https://extroverting.com/tag/nj-com/
https://extroverting.com/tag/boston-herald/
https://extroverting.com/tag/washington-post/

I'll dig into these changes 
https://github.com/smcnally/extro-hueman-pro-child/commit/7a7535d5376806e37388a9d656e11c8c0992ea2c

and report back Thursday (18.02.22)

**Comment by smcnally** [comment]
> If it doesn't work for you, please describe which plugins or which code updates you are using to add custom avatars to users.

No custom code for avatars. Using gravatar with default functionality. 
`get_avatar($user_ID)` will work (vs `get_user_meta($user_ID, 'wp_user_avatar'` -- which is handy to keep around / comment out [not delete])

boston-herald: (uid: 17)
https://en.gravatar.com/userimage/9107/098a0692e29330f2ad1d0a32e56c82c6.jpg

nj-com: (uid: 19)
https://en.gravatar.com/userimage/9107/10bd8b4517436fabf3afb7ca8742eb6c.jpg

washington-post: (uid: 18)
https://en.gravatar.com/userimage/9107/2fe9280950639cf7593399326da98317.jpg

**Comment by smcnally** [comment]
Latest db dump from Production:

https://extroverting.com/2018-02-21-20-16.gz

**Comment by FARCreative** [comment]
Thank you for the new database. Since users' avatars are stored on gravatar I have added additional search for the logos. Function get_user_meta searches the logo as a local attachment. If logo is not found, we search in the Gravatar using get_avatar_url function.  I have uploaded changes to 'farcreative' branch. Please test if it works on your side.

**Comment by smcnally** [comment]
excellent, Evgeny. your latest updates look good and are Working as Designed on the front-end:

![image](https://user-images.githubusercontent.com/850878/36562215-5104df76-17e4-11e8-9296-cd89cd13c48c.png)

![image](https://user-images.githubusercontent.com/850878/36562227-591385d2-17e4-11e8-8eb1-738aad5a33f9.png)

https://extroverting.com/tag/nj-com/
https://extroverting.com/tag/washington-post/

will leave '**farcreative**' the active branch in Prod, review the updates, create a PR, merge with master, and close this when that's completed. many thanks.

**Comment by smcnally** [comment]
all good, merged - https://github.com/smcnally/extro-hueman-pro-child/pull/3
