### ISSUE TITLE
Promote preferred Author posts on Page 1 of archive

### ISSUE THREAD

**Issue by smcnally** [smcnally/extro-hueman-pro-child#4]
For the first page of all `archive` (tag and category) pages, we will fill **the first post slots** from a list of preferred Author IDs who have a post using that tag or category.

(This issue is related to https://github.com/smcnally/extro-hueman-pro-child/issues/1 . We've Simplified the logic here and will be able to close #1 if this makes more sense.) 

Our preferred Authors are **IDs 9, 15**, e.g. 
so for [**/investing**](https://extroverting.com/tag/investing/): 

We _first_ look at posts from author **IDs 9, 15** for posts tagged **investing**.  
take the most-recent post tagged **investing** from **UID 9**, 
and the most-recent post tagged **investing** from **UID 15**,
and add these as the first two post slots on **Page 1** of **/investing**.
Fill the rest of Page 1 -- and all further **/investing** pages -- with the most-recent posts from all other UIDs (as it is done currently). 

No special styles or formatting is required for the preferred author posts. 
They should be "sticky" to the archive page until they are replaced by more-recent post(s) from preferred authors. 

we should use the child theme files as needed:

```
extro-hueman-pro-child/archive.php
extro-hueman-pro-child/tmpl/archive-tmpl
extro-hueman-pro-child/parts/post-list-articles
```

Creating the preferred Author array and filtering posts by each
(from https://stackoverflow.com/posts/45563266/revisions) : 

```
// Preferred Authors:
$users_id_array = array('9','15');

// Get all posts by these authors
$query = new WP_Query( array( 
    'post_type' => 'post',
    'author__in' => $users_id_array
) );
```

**Comment by FARCreative** [comment]
I have made adjustments in the code and removed stylization for the preffered posts.
Our code searches latest post for each of the preffered authors  in current category or tag, then we remove these posts from the listing and add to the top of the list. 
I did't find "Investing" tag and posts that belong to authors with id 9 and 15 in the database, so I have added "Investing" tag and assigned it 
 to some posts. Also I have assigned these preferred authors manually to some posts tagged with "Investing". It works on my end. 
If doesn't work on your site, please send me your current database again.

**Comment by smcnally** [comment]
Looks good from the front end. **category** and **tag** (`archive`) pages follow the logic you note / we've discussed. e.g. these archive pages have appropriate posts from UIDs 9 and 15:

https://extroverting.com/category/states/mi/
https://extroverting.com/category/the-law/
https://extroverting.com/tag/crime/

Will review the code, make notes of questions or comments, create the PR, and merge `farcreative` with `master`.  many thanks

**Comment by smcnally** [comment]
merged
