### ISSUE TITLE
 New post format - SourceItem

### ISSUE THREAD

**Issue by smcnally** [smcnally/extro-hueman-pro-child#8]
Start with a Standard post. **SourceItem** has all the same display rules on index, archive, search pages.

One difference is **SourceItem** headlines link directly to the source URL (`wprss_item_permalink` in `postmeta`) rather than the post (`single.php`) 

In this example, "Unlicensed medical marijuana facilities to close" is SourceItem format. 
The headline links directly to https://www.wxyz.com/news/unlicensed-operation-of-medical-marijuana-facilities-to-end-oct-31-under-new-rules and not https://extroverting.com/2018/10/01/portland-adopts-moratorium-on-establishing-certain-medical-marijuana-operations/

For style, `article` elements for SourceType formats: 

"background-color: #e4f8d2;"
and a blue border 2px 

![image](https://user-images.githubusercontent.com/850878/46333967-33a6a580-c5d7-11e8-866a-195e7029e1c3.png)

**Comment by FARCreative** [comment]
I have created 'farcreative' branch and upload our code there. I have created a new post with "Link" format and filled title, content, excerpt, link tile(this field is not used on the site), link URL fields. It looks like on the screenshot in my local copy of the site.
![extroverting-local](https://user-images.githubusercontent.com/1779096/46498065-5fe64000-c7ea-11e8-9d01-e8073796dab4.png)

**Comment by smcnally** [comment]
Excellent. Will review this, add any questions here, and close this ticket - Thank you

**Comment by smcnally** [comment]
Looks good, thank you. The farcreative branch is live on https://extroverting.com

I've left two comments in your commit - 

[Check explicitly for the post format ](https://github.com/smcnally/extro-hueman-pro-child/commit/279918e53711604117f8f21eec97f427c7d19f83#r30781167)
Don't presume everything with a `source_item_url` value  is post format link 
Don't automatically set post format to link 

[Remove 'www.' when displaying `source_item_url`](https://github.com/smcnally/extro-hueman-pro-child/commit/279918e53711604117f8f21eec97f427c7d19f83#r30781200)

**Comment by FARCreative** [comment]
Check explicitly for the post format  **Done**
Don't automatically set post format to link  **Default post format is "Standart"**
Remove 'www.' when displaying source_item_url  **Done**

**Comment by smcnally** [comment]
We are where we want to be here -- thank you. 

I've left a message on your commit to note changed I've made to `content.php `
